# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 917b2d81bcb0e8ee9fe860d68be83465ea1b3b2f701142532b32a3b77750407c07f87c17cb8ebac1a7081d01328fb6b7af505120e85e544ca90291c3d3319c1e

test:
  secret_key_base: 2e6769d8d4d3b377f85c101838ac2767825c7bd077e2a553d405ac05d3ac7910c89e0c0fb47ca94579a93babb20bb4745d4d0f6273829abfd93b53a78868ce81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
